"""Initial schema

Revision ID: 662d4e19a4fc
Revises: 
Create Date: 2026-07-08 21:20:57.728888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '662d4e19a4fc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stadiums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cfbd_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=30), nullable=True),
    sa.Column('timezone', sa.String(length=100), nullable=True),
    sa.Column('elevation', sa.Float(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('construction_year', sa.Integer(), nullable=True),
    sa.Column('grass', sa.Boolean(), nullable=True),
    sa.Column('dome', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cfbd_id')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school', sa.String(length=100), nullable=False),
    sa.Column('abbreviation', sa.String(length=100), nullable=True),
    sa.Column('mascot', sa.String(length=50), nullable=True),
    sa.Column('conference', sa.String(length=100), nullable=True),
    sa.Column('division', sa.String(length=100), nullable=True),
    sa.Column('classification', sa.String(length=100), nullable=True),
    sa.Column('color', sa.String(length=100), nullable=True),
    sa.Column('alternate_color', sa.String(length=100), nullable=True),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('stadium_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stadium_id'], ['stadiums.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teams')
    op.drop_table('stadiums')
    # ### end Alembic commands ###
